### ISSUE TITLE
Submit sequencing data to NCBI

### ISSUE THREAD

**Issue by kubu4** [sr320/ceabigr#100]

**Comment by kubu4** [comment]
Update: Data upload has been completed.

Working on required NCBI metadata to complete submission.

**Comment by yaaminiv** [comment]
@kubu4 do we have BioProject numbers/other info yet I can include in the paper?

**Comment by kubu4** [comment]
Yes! Just got this finished up late Monday and am still in process of getting junk entered into notebook.

[PRJNA1089235](https://www.ncbi.nlm.nih.gov/sra/PRJNA1089235)
