### ISSUE TITLE
S2 file blank

### ISSUE THREAD

**Issue by yaaminiv** [sr320/ceabigr#110]
@kubu4 Where can I find a version of this file that has information in it?  https://github.com/sr320/ceabigr/blob/main/supplemental-files/S2-01.01-fmcoe-max-predom-isos-gene_fpkm.csv

**Comment by sr320** [comment]
-> https://raw.githubusercontent.com/sr320/ceabigr/752a0e1d7c0521b02c93a07f7b66ad2983afbc80/supplemental-files/01.01-fmcoe-max-predom-isos-gene_fpkm.csv

**Comment by yaaminiv** [comment]
thanks!
