### ISSUE TITLE
Calculate gene-level methylation statistics in oyster data

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#13]
Relevant files are at 
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/120321-cvBS/

for instance for each sample 

```
3F_R1_val_1_10x.bedgraph  3F_R1_val_1_bismark_bt2_pe.deduplicated.bam             3F_R1_val_1.CpG_report.merged_CpG_evidence.cov
3F_R1_val_1_10x.tab       3F_R1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz  3F_R1_val_1.CpG_report.txt
3F_R1_val_1_5x.bedgraph   3F_R1_val_1_bismark_bt2_pe.deduplicated.sorted.bam
3F_R1_val_1_5x.tab        3F_R1_val_1_bismark_bt2_pe.deduplicated.sorted.bam.bai
```

**Comment by sr320** [comment]
easy way to grab
```
wget -r \
--no-check-certificate \
--quiet \
--no-directories --no-parent \
-P . \  #where files go - indicating current directory
-A *10x.tab  \ #which files you want
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/120321-cvBS/
```

**Comment by shellytrigg** [comment]
script for gene methylation from methcompare: 
https://github.com/hputnam/Meth_Compare/blob/master/code/Median-Methylation-Calculations.Rmd

**Comment by sr320** [comment]
IS this complete @shellytrigg ?

**Comment by sr320** [comment]
this might be it https://github.com/sr320/ceabigr/blob/main/RAnalysis/data/meanmethgene_10x_allsampssex.csv

**Comment by sr320** [comment]
Went on to create male and female file and gene meth difference (exposed - control)

https://github.com/sr320/ceabigr/tree/main/output/73-gene-methylation

**Comment by sr320** [comment]
and separate set based on what was derived in code 40 at
https://github.com/sr320/ceabigr/tree/main/output/73-gene-methylation
