### ISSUE TITLE
Problem downloading Husky OnNet

### ISSUE THREAD

**Issue by AHuffmyer** [sr320/ceabigr#14]
I tried to download Husky OnNet using my UW NetID for RStudio access. When I try to download I get redirected to a page that says "unauthorized". Has anyone else had this issue?

**Comment by AHuffmyer** [comment]
![Screen Shot 2022-02-14 at 11 41 45](https://user-images.githubusercontent.com/32178010/153934744-410937ee-f960-4fb7-ae17-46aa67637845.png)

**Comment by kubu4** [comment]
Do you have a password for accessing stuff in your UW account?

**Comment by AHuffmyer** [comment]
I have my UW NetID password - is that the same?

**Comment by AHuffmyer** [comment]
I wonder if my NetID has to be assigned to allow access to Husky OnNet

**Comment by kubu4** [comment]
> I have my UW NetID password - is that the same?

You should have a UW NetID and a password assigned to you for accessing University of Washington services. Is that the password you used when attempting to download Husky OnNet?

**Comment by sr320** [comment]
@AHuffmyer what is your UW ID?

**Comment by AHuffmyer** [comment]
Thank you @sr320 that worked!

**Comment by AHuffmyer** [comment]
@sr320 and @kubu4 - I closed the issue too early. I was able to successfully downloaded Husky OnNet, but received this error when trying to activate the VPN. 
<img width="615" alt="Screen Shot 2022-02-14 at 12 30 31" src="https://user-images.githubusercontent.com/32178010/153941652-2bf9467f-d8c3-458a-9267-0ee3d8578cd0.png">

**Comment by sr320** [comment]
You are sponsored.. see https://d.pr/i/3m0s7x
maybe it takes a bit to kick in..

**Comment by AHuffmyer** [comment]
Sounds good. Iʻll confirm when I try again in a little while. Thank you!

**Comment by kubu4** [comment]
What instructions are provided in that link that it asks you to click on?

**Comment by AHuffmyer** [comment]
It just logs me out... Iʻll try to log back in tomorrow - perhaps it takes some time. 

<img width="204" alt="Screen Shot 2022-02-14 at 12 56 42" src="https://user-images.githubusercontent.com/32178010/153945341-fa99e658-b067-490c-a592-2cb323a45102.png">

**Comment by kubu4** [comment]
I think that link should go here:

https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#special

Please try those instructions and see what happens.

**Comment by kubu4** [comment]
Thanks.

Oddly, when you click on the link, it thanks you for logging out (suggesting you might actually be logged in).

Can you please re-launch Husky OnNet and then visit this URL? 

https://husky-onnet-test.uw.edu/vpn-test/

That'll tell you if you're successfully connecting.

**Comment by kubu4** [comment]
I'd probably just hit up UW-IT at this point, though. They're very helpful and pretty responsive: help@uw.edu

**Comment by AHuffmyer** [comment]
Iʻll do that - thank you!

**Comment by AHuffmyer** [comment]
Problem Solved!! We have to edit the server address to access for sponsored ID's. Here are the steps I followed once I had Husky OnNet downloaded (Mac): 

1. Open the BIG-IP client
2. Click "Manage VPN Servers" in the menu bar (selecting the BIG-IP icon from the top right hand bar on your computer). 
3. Click the + to add a new server. Name = Campus Sponsor; Server Address = https://dept-huskyonnet.uw.edu/spon
4. Click Modify.
5. Click the + to add a new server. Name = All Internet Sponsor; Server Address = https://dept-huskyonnet-ns.uw.edu/spon
6. Click Modify and close the window.
7. Select "Campus Sponsor" from the menu bar.
8. Now select VPN On from the menu bar. 
9. This should connect you to the VPN!

More information can be found on this page: https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored

**Comment by laurahspencer** [comment]
@AHuffmyer this was super helpful, thanks for posting the steps to add new servers!
