### ISSUE TITLE
Requested Access to RStudio Server

### ISSUE THREAD

**Issue by emmastrand** [sr320/ceabigr#16]
Not an existing UW employee/student so no NetID yet. emma_strand@uri.edu 

Thank you!!

**Comment by kubu4** [comment]
Also, please visit this page and make sure that Husky OnNet is listed as an "Active service": https://uwnetid.washington.edu/manage/?service

**Comment by emmastrand** [comment]
I'm experiencing the same issues that @AHuffmyer did in her issue post. Ariana, did you get an answer from IT?

**Comment by AHuffmyer** [comment]
I am making progress and almost have it solved! Have you been able to download Husky OnNet?

**Comment by emmastrand** [comment]
I can download Husky OnNet but stuck on the same error when trying to activate the VPN. The screenshot of "Need to use sponsored UW netID servers to connect to this service". And when I click the link it gives the same "Your session has finished" message.

**Comment by AHuffmyer** [comment]
Problem solved on my end! We have to edit the server address to access for sponsored ID's. Here are the steps I followed once I had Husky OnNet downloaded (Mac):

1. Open the BIG-IP client
2. Click "Manage VPN Servers" in the menu bar (selecting the BIG-IP icon from the top right hand bar on your computer).
3. Click the + to add a new server. Name = Campus Sponsor; Server Address = https://dept-huskyonnet.uw.edu/spon
4. Click Modify.
5. Click the + to add a new server. Name = All Internet Sponsor; Server Address = https://dept-huskyonnet-ns.uw.edu/spon
6. Click Modify and close the window.
7. Select "Campus Sponsor" from the menu bar.
8. Now select VPN On from the menu bar.

This should connect you to the VPN!

More information can be found on this page: https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored

**Comment by kubu4** [comment]
RStudio Server account created. Credentials/URL sent via Slack.

Thanks for your patience and thanks to @AHuffmyer for the troubleshooting!
