### ISSUE TITLE
Requesting access to UW RStudio server 

### ISSUE THREAD

**Issue by JillAshey** [sr320/ceabigr#17]
Email: jillashey@uri.edu

**Comment by jarcasariego** [comment]
Can I be added too? Thanks
Email: javirodr@fiu.edu

**Comment by kubu4** [comment]
Thanks, @jarcasariego. Proceed to [Step #3 of the RStudio Server Instructions](https://github.com/sr320/ceabigr/wiki/RStudio-Server-Instructions).


NOTE: You may have to follow some of the instructions here to get the Husky OnNet service configured for your type of UW NetID ("sponsored"):

https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored


After you download/install/configure/launch Husky OnNet, visit this URL to test whether or not it's working correctly:

https://husky-onnet-test.uw.edu/vpn-test/

Please report back here with status.

**Comment by kubu4** [comment]
Also, please visit this page and make sure that Husky OnNet is listed as an "Active service": https://uwnetid.washington.edu/manage/?service

**Comment by jarcasariego** [comment]
Thanks @kubu4. Everything smooth. My UW NetID is javirodr

**Comment by kubu4** [comment]
Thanks, @JillAshey. 

NOTE: You may have to follow some of the instructions here to get the Husky OnNet service configured for your type of UW NetID ("sponsored"):

https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored

Also, please visit this page and make sure that Husky OnNet is listed as an "Active service": https://uwnetid.washington.edu/manage/?service

After you download/install/configure/launch Husky OnNet, visit this URL to test whether or not it's working correctly:

https://husky-onnet-test.uw.edu/vpn-test/

Please report back here with status.

**Comment by shaylematsuda** [comment]
HI Can I please be added, too?
shaylematsuda@gmail.com
(or smatsuda@sheddaquarium.org if it needs to be institutional)

**Comment by kubu4** [comment]
Thanks, @shaylematsuda .

NOTE: You may have to follow some of the instructions here to get the Husky OnNet service configured for your type of UW NetID ("sponsored"):

https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored

Also, please visit this page and make sure that Husky OnNet is listed as an "Active service": https://uwnetid.washington.edu/manage/?service

After you download/install/configure/launch Husky OnNet, visit this URL to test whether or not it's working correctly:

https://husky-onnet-test.uw.edu/vpn-test/

Please report back here with status.

**Comment by kubu4** [comment]
Sent @laurahspencer login info via Slack.

**Comment by laurahspencer** [comment]
RStudio Server access achieved.

**Comment by JillAshey** [comment]
My UW NetID is: jashey 

When downloading and attempting to log on to the UW server, it gives me this error:

<img width="1227" alt="Screen Shot 2022-02-16 at 2 47 19 PM" src="https://user-images.githubusercontent.com/63874927/154344075-1f5737e1-cca2-44f2-b160-aee7c8a8b32a.png">

**Comment by kubu4** [comment]
@JillAshey - Please see possible solution from @AHuffmyer:

https://github.com/sr320/ceabigr/issues/14#issuecomment-1040508734

Report back to let me know how it goes.

**Comment by ksil91** [comment]
ksil91@gmail.com

**Comment by kubu4** [comment]
Sent @JillAshey RStudio Server info via Slack.

**Comment by zbengt** [comment]
Asking for an add late in the game. UW net ID/email: zbengt@uw.edu

**Comment by kubu4** [comment]
Thanks, @ksil91.

NOTE: You may have to follow some of the instructions here to get the Husky OnNet service configured for your type of UW NetID ("sponsored"):

https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/#Sponsored

Also, please visit this page and make sure that Husky OnNet is listed as an "Active service": https://uwnetid.washington.edu/manage/?service

After you download/install/configure/launch Husky OnNet, visit this URL to test whether or not it's working correctly:

https://husky-onnet-test.uw.edu/vpn-test/

Please report back here with status.

P.S. You may need to refer to this guide by @AHuffmyer:

https://github.com/sr320/ceabigr/issues/14#issuecomment-1040508734

**Comment by ksil91** [comment]
@kubu4 vpn working, username is ksil91

**Comment by kubu4** [comment]
Sent @ksil91 RStudio Server info via Slack.

**Comment by shellytrigg** [comment]
@kubu4 can you please add shellywanamaker@gmail.com ?

**Comment by kubu4** [comment]
@shellytrigg - UW IT request has been initiated. Not entirely sure if UW Husky OnNet access request is auto-processed or has to be human-approved. If it requires human review, the request probably won't be processed for a few hours. Regardless, please be sure to check your Spam folder; I think Katherine's approval may have been sitting in her Spam folder for a day and half before she realized it.

**Comment by sr320** [comment]
Thanks- do not need On-net while at FHL

**Comment by kubu4** [comment]
Ah! Even better! Thanks for clarifying! Adding RStudio Access mementarily!

**Comment by kubu4** [comment]
Sent @shellytrigg RStudio Server info via Slack.

**Comment by sr320** [comment]
Does @shaylematsuda have Rstudio server acount?

**Comment by kubu4** [comment]
Sent @shaylematsuda RStudio Server info via Slack.

Sorry for the delay!!
