### ISSUE TITLE
I need authorization for Husky OnNet 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/ceabigr#19]
I have a similar issue as Ariana had (#14) - I'll need my UW NetID to be authorized to access Husky OnNet: 

UW NetID: lhs3
email: lhs3@uw.edu

Also curious is the VPN provides access to UW Library system?  I'm currently not authorized to get papers through UW.
Thanks!

**Comment by kubu4** [comment]
I've authorized Husky OnNet for your UW NetID.

Make sure it's an "Active service" here: https://uwnetid.washington.edu/manage

> Also curious is the VPN provides access to UW Library system?

It may not. Depends on how @sr320 set up your UW NetID when it got re-instated. Library access is generally a more restricted UW service, so access is limited to only certain types of UW NetIDs (e.g. "Sponsored with deferred identity verification" do not get access to UW Libraries).

SciHub's a great resource in the interim: 

https://sci-hubtw.hkvisa.net/
