### ISSUE TITLE
Credentials for BIG-IP Edge Client

### ISSUE THREAD

**Issue by yaaminiv** [sr320/ceabigr#20]
I tried using my  UW net ID (yaaminiv) with BIG-IP Edge Client/Husky OnNet and got the following error:

<img width="730" alt="Screen Shot 2022-02-15 at 4 01 03 PM" src="https://user-images.githubusercontent.com/22335838/154148434-1345f36b-f9c0-4b89-98d9-45522fb064b1.png">

Do I need a new UW net ID in order to get access, or does something need to be done about the access my current net ID has?

Assuming this may affect @laurahspencer as well...

**Comment by kubu4** [comment]
I've authorized Husky OnNet for your UW NetID.

Make sure it's an "Active service" here: https://uwnetid.washington.edu/manage

**Comment by yaaminiv** [comment]
Followed @AHuffmyer's [instructions](https://github.com/sr320/ceabigr/issues/14#issuecomment-1040508734) and now have access to the VPN! Just need RStudio server login credentials.

**Comment by kubu4** [comment]
RStudio info sent via Slack.
