### ISSUE TITLE
Access Request RStudio Server - Putnam

### ISSUE THREAD

**Issue by hputnam** [sr320/ceabigr#24]

**Comment by hputnam** [comment]
hputnam@uri.edu here is my email address @kubu4

**Comment by kubu4** [comment]
UW IT request has been issues. Not entirely sure if UW Husky OnNet access request is auto-processed or has to be human-approved. If it requires human review, the request probably won't be processed for a few hours. Regardless, please be sure to check your Spam folder; I think Katherine's approval may have been sitting in her Spam folder for a day and half before she realized it.

**Comment by sr320** [comment]
Thanks- do not need On-net while at FHL

**Comment by kubu4** [comment]
Ah! Even better! Thanks for clarifying! Adding RStudio Access mementarily!

**Comment by kubu4** [comment]
Sent @hputnam RStudio Server info via Slack.
