### ISSUE TITLE
Determine TE copy number variation

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#25]

**Comment by sr320** [comment]
if you want sorted, deduplicated bams from Bismark

```
wget -r \
--no-check-certificate \
--quiet \
--no-directories --no-parent \
-P . \  #where files go - indicating current directory
-A *sorted.bam \
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/071521-cvBS/
```

**Comment by sr320** [comment]
two TE tracks

[C_virginica-3.0_TE-all.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/C_virginica-3.0_TE-all.gff) : http://owl.fish.washington.edu/halfshell/genomic-databank/C_virginica-3.0_TE-all.gff

MD5 = d0d81fc6cf7525bc2c61984bee23521b

[Details](http://onsnetwork.org/kubu4/2018/08/28/transposable-element-mapping-crassostrea-virginica-genome-cvirginica_v300-using-repeatmasker-4-07/)

[C_virginica-3.0_TE-Cg.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/C_virginica-3.0_TE-Cg.gff) : http://owl.fish.washington.edu/halfshell/genomic-databank/C_virginica-3.0_TE-Cg.gff

MD5 = 83cd753c171076464fee1165b7e1c6ba

[Details](http://onsnetwork.org/kubu4/2018/08/28/transposable-element-mapping-crassostrea-virginica-genome-cvirginica_v300-using-repeatmasker-4-07/)

**Comment by yaaminiv** [comment]
@jarcasariego fasta.out can be found through these links:

https://robertslab.github.io/sams-notebook/2018/05/29/transposable-element-mapping-crassostrea-virginica-ncbi-genome-assembly-using-repeatmasker-4-07.html

https://robertslab.github.io/sams-notebook/2018/08/28/transposable-element-mapping-crassostrea-virginica-genome-cvirginica_v300-using-repeatmasker-4-07.html

TE-all: All species used for TE identification
TE-Cg: Only *C. gigas* used for TE identification

**Comment by jarcasariego** [comment]
for f in *.bam; do /home/shared/samtools-1.12/samtools depth ${f} > ${f}_depth
> done

**Comment by sr320** [comment]
I generated files for each sample at https://github.com/sr320/ceabigr/tree/main/output

*_te-allcov_m.out
