### ISSUE TITLE
Generate count matrix of sequence counts per exon per gene

### ISSUE THREAD

**Issue by AHuffmyer** [sr320/ceabigr#26]

**Comment by AHuffmyer** [comment]
[exon.bed.zip](https://github.com/sr320/ceabigr/files/8111835/exon.bed.zip)
Exon bed file here

**Comment by sr320** [comment]
is this completed?

**Comment by AHuffmyer** [comment]
Not completed yet

**Comment by AHuffmyer** [comment]
AH - run transcript count matrix against exon gff file
