### ISSUE TITLE
BAM files for gene expression analysis

### ISSUE THREAD

**Issue by JillAshey** [sr320/ceabigr#29]
@yaaminiv @sr320 Where are the HISAT2 code and/or BAM files for the RNASeq gene expression analysis located?

**Comment by sr320** [comment]
check out https://robertslab.github.io/sams-notebook/2022/01/31/RNAseq-Alignment-C.virginica-Adult-OA-Gonad-Data-to-GCF_002022765.2-Genome-Using-HISAT2-on-Mox.html

**Comment by sr320** [comment]
There are links there that walk you back eg https://robertslab.github.io/sams-notebook/2021/07/20/Genome-Annotations-Splice-Site-and-Exon-Extractions-for-C.virginica-GCF_002022765.2-Genome-Using-Hisat2-on-Mox.html

**Comment by sr320** [comment]
Looks like BAMs are at https://gannet.fish.washington.edu/Atumefaciens/20210726_cvir_stringtie_GCF_002022765.2_isoforms/

**Comment by sr320** [comment]
BUT this might be what you are looking for https://github.com/sr320/ceabigr/issues/15

**Comment by sr320** [comment]
@JillAshey are these in hand? can we close this issue?
