### ISSUE TITLE
% methylation matrix of intersecting loci ?

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#31]
hu Laura
yes - @yaaminiv will post soon

**Comment by yaaminiv** [comment]
@laurahspencer @ksil91 

union bedgraph: https://gannet.fish.washington.edu/seashell/ceabigr/output/methylation-landscape/union_10x.bedgraph

union bedgraph with a column for avg meth across samples: https://gannet.fish.washington.edu/seashell/ceabigr/output/methylation-landscape/union-averages.bedgraph

code: https://github.com/sr320/ceabigr/blob/main/code/General-Methylation-Landscape.ipynb
