### ISSUE TITLE
awk code for replacing loci %meth where snp with 0

### ISSUE THREAD

**Issue by shellytrigg** [sr320/ceabigr#33]
@yaaminiv 

awk -F"\t" 'NR==FNR{a[$1,$2]=$1"\t"$2;next}(if($1"\t"$2) in a){print $1"\t"$2"\t"$3"\t"0;else print $0}' .vcf .bedgraph

**Comment by yaaminiv** [comment]
awk -F"\t" 'NR==FNR{a[$1"\t"$2]=$1"\t"$2;next}{if(($1"\t"$2) in a) print $1"\t"$2"\t"$3"\t"0;else print $0}' \
3F_R1_val_1_bismark_bt2_pe.SNP-results.vcf \
3F_R1_val_1_10x.sort.bedgraph

it works!!
