### ISSUE TITLE
Remake genome feature tracks

### ISSUE THREAD

**Issue by yaaminiv** [sr320/ceabigr#34]
not urgent, but should make sure tracks don't have overlapping features

**Comment by yaaminiv** [comment]
issues with accessing genome feature tracks: https://github.com/sr320/ceabigr/issues/39

**Comment by sr320** [comment]
Why not use NCBI gff file?

**Comment by yaaminiv** [comment]
can use, I just want to remake the flanking and intergenic tracks specifically (not included in NCBI gff) to ensure that there are no overlapping features.
