### ISSUE TITLE
install numpy for python3 in raven

### ISSUE THREAD

**Issue by jarcasariego** [sr320/ceabigr#35]
@kubu4 is it possible to get numpy installed in raven?

**Comment by kubu4** [comment]
The simplest means to do so is to download and install [Anaconda for Linux](https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh):

`wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh`

Run that script:

`bash Anaconda3-2021.11-Linux-x86_64.sh`

Follow instructions (I think you want to answer "yes" to all questions).

After install, run:

`conda install numpy`

**Comment by jarcasariego** [comment]
done! Thanks @kubu4

**Comment by kubu4** [comment]
Out of curiosity, which approach did you use?

**Comment by jarcasariego** [comment]
the second one.
