### ISSUE TITLE
Raw per-gene counts from RNASeq data (not normalized)

### ISSUE THREAD

**Issue by laurahspencer** [sr320/ceabigr#37]
I'm looking for raw gene counts per individual from the aligned RNASeq data.  @kubu4 does this exist? I see the file gene_fpkm.txt, so looking for that but not normalized.

**Comment by kubu4** [comment]
Sorry, what do you mean by raw gene counts?

**Comment by laurahspencer** [comment]
I think this is what I needed, the transcripts per gene per sample file 

https://github.com/epigeneticstoocean/2018_L18-adult-methylation/blob/main/analyses/transcript-counts_per-gene-per-sample.csv?raw=true
