### ISSUE TITLE
CG_motif file location?

### ISSUE THREAD

**Issue by jarcasariego** [sr320/ceabigr#39]
the file located here "https://eagle.fish.washington.edu/Cvirg_tracks/C_virginica-3.0_CG-motif.bed" is not there anymore. 

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://eagle.fish.washington.edu/Cvirg_tracks/C_virginica-3.0_CG-motif.bed">here</a>.</p>
</body></html>

**Comment by yaaminiv** [comment]
try from this location: https://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/yaamini-virginica/analyses/2019-05-13-Generating-Genome-Feature-Tracks/
