### ISSUE TITLE
Missing samples from the gene_fpkm.csv file 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/ceabigr#44]
Looks like we're missing data for 4 samples (only have 22 out of the 26 RNASeq .bam files).

**Comment by sr320** [comment]
26 bam files are here https://gannet.fish.washington.edu/Atumefaciens/20210726_cvir_stringtie_GCF_002022765.2_isoforms/

**Comment by sr320** [comment]
sounds like https://github.com/epigeneticstoocean/2018_L18-adult-methylation/blob/main/analyses/gene_fpkm.csv


is incomplete?

**Comment by kubu4** [comment]
Hmmm... Four samples (no sure which ones yet) get dropped during this merge step:

https://github.com/epigeneticstoocean/2018_L18-adult-methylation/blob/fd53c74e8838f0d277043d6180f4f698612e6a45/code/ballgown_analysis.Rmd#L727

Not sure I have the availability to troubleshoot for long, so if someone can also investigate (maybe it's a simple problem with the `merge()` command I implemented), that'd be killer.

**Comment by kubu4** [comment]
Okay, found the issue. Substring command leaves an errant `.` in four sample names. Will work on fix...

**Comment by kubu4** [comment]
Fixed with this [commit](https://github.com/epigeneticstoocean/2018_L18-adult-methylation/commit/1d9c6dfd954782130b8c17266f3582cb6dc1b9c1).
