### ISSUE TITLE
install nextflow on Raven

### ISSUE THREAD

**Issue by shellytrigg** [sr320/ceabigr#47]
here's a log with how I installed nextflow on mox and on roadrunner. @ksil91 you can reference the part of the roadrunner part of the log:

https://github.com/shellytrigg/Salmon_sealice/blob/master/analyses/20201027/install_nf-core_Nextflow.log

**Comment by ksil91** [comment]
Instructions for nextflow: https://www.nextflow.io/

instructions for epidiverse
https://github.com/EpiDiverse/snp

**Comment by ksil91** [comment]
https://docs.docker.com/engine/install/

sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get install \
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

**Comment by sr320** [comment]
should be installed
