### ISSUE TITLE
Test code reproducibility for RNAseq data

### ISSUE THREAD

**Issue by kubu4** [sr320/ceabigr#50]
Well, it appears I may have submarined a decent chunk of CEABIGR (temporarily).

Initial RNAseq alignments (BAM) for individuals was performed using _untrimmed_ reads!

So, any analysis (including my previous `ballgown` analyses) should be disregarded.

I'm in the process of re-running things. Will report back here when things are ready to test everyone's code reproducibility!

So sorry to everyone involved in this!

**Comment by sr320** [comment]
No problem.. most of the work is still in the phase of developing the pipelines, so it can continue, and simple insert new files. Noting there is a contingent that beliefs trimming in RNAseq is not necessary.
