### ISSUE TITLE
Update Gene Expression Data files

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#53]
Once trimmed data gets through pipeline update files
at 
https://github.com/sr320/ceabigr/wiki/Gene-Expression-Data-Types

also on page provide links to sorted bam.

**Comment by sr320** [comment]
But do not all the other links on that page need to be updated? Revision history looks like only `bams` added?

**Comment by kubu4** [comment]
URLs to files won't change, but file contents do. Check revision history in analysis directory, not Wiki

**Comment by sr320** [comment]
can you let me know when all the updated gene expression files have been updated?

**Comment by kubu4** [comment]
They're updated

**Comment by sr320** [comment]
what about https://github.com/epigeneticstoocean/2018_L18-adult-methylation/blob/main/data/fpkm-all_transcripts.csv ?

**Comment by kubu4** [comment]
Good catch! Sorry! That's not in any of the R Markdown scripts I have, so it got missed.

I'll probably be able to get it re-generated this evening, but more likely first thing tomorrow morning.

**Comment by sr320** [comment]
Thanks, but that is not the only one.. 

>  Check revision history in analysis directory, not Wiki 
😄

**Comment by kubu4** [comment]
Ha! Good point! Forgot I decided to break out stuff into other scripts to keep things a bit easier to manage. LOL!

**Comment by kubu4** [comment]
Think I got 'em all, finally!

**Comment by sr320** [comment]
getting some 404s https://github.com/sr320/ceabigr/wiki/Gene-Expression-Data-Types#cov-in-transcript

**Comment by kubu4** [comment]
Where?

**Comment by kubu4** [comment]
NM!
