### ISSUE TITLE
Increasing threads in GATK?

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#58]
As @laurahspencer warned, the following takes a long time (another month)

```
echo "Calling variants using HaplotypeCaller"
for file in *dedup-split-RG.bam
do
sample="$(basename -a $file | cut -d "." -f 1)"

/home/shared/gatk-4.2.5.0/gatk HaplotypeCaller \
-R /home/shared/8TB_HDD_01/sr320/github/ceabigr/data/Cvirginica_v300.fa \
-I $sample.dedup-split-RG.bam \
-O $sample.variants.g.vcf \
-ERC GVCF
done >> HaplotypeCaller_stout.txt 2>&1
```

Is there a way I can increase # threads / memory? I found a few options online but just curious if @ksil91 or others have recommendations before I go down the path of installing new stuff.

**Comment by ksil91** [comment]
Agree about splitting into intervals. I haven't needed to do it myself but it seems to be commonly used. You can also request more threads with this (here asking for 5):

`--native-pair-hmm-threads 5`

**Comment by laurahspencer** [comment]
For the interval option, it looks like that script I sent you already preps and uses an interval list for the `gatk GenomicsDBImport` step (next one after `HaplotypeCaller`). 
```
# create interval list (just a list of all contigs in genome)
echo "Creating intervals list"
awk 'BEGIN {FS="\t"}; {print $1 FS "0" FS $2}' ${REF}/Paralithodes_platypus_genome.fasta.fai > intervals.bed
```

**Comment by laurahspencer** [comment]
I haven't gotten to that step, yet, in my current job so can't confirm that it's foolproof - I'd double check that it's doing what you want before using that code.

**Comment by sr320** [comment]
FTR increasing threads really does not speed anything up. I have yet to try intervals. I will try just intervalling into chromosomes (~11) and see if that makes a difference.

**Comment by sr320** [comment]
note that using intervals in this case is slower...
eg

```
source /gscratch/srlab/programs/scripts/paths.sh

for file in *dedup-split-RG.bam
do
sample="$(basename -a $file | cut -d "." -f 1)"

/gscratch/srlab/programs/gatk-4.1.9.0/gatk HaplotypeCaller \
-R Cvirginica_v300.fa \
-I $sample.dedup-split-RG.bam \
-O $sample.variants.g.vcf \
--native-pair-hmm-threads 12 \
-ERC GVCF
done
``` 
 is running faster than 

```
for file in ../031722-haplo/*dedup-split-RG.bam
do
sample="$(basename -a $file | cut -d "." -f 1)"

/gscratch/srlab/programs/gatk-4.1.9.0/gatk HaplotypeCaller \
-R ../031722-haplo/Cvirginica_v300.fa \
-L interval.bed \
-I ../031722-haplo/$sample.dedup-split-RG.bam \
-O $sample.variants.g.vcf \
--native-pair-hmm-threads 28 \
-ERC GVCF
done

```

though as you can see I did not keep threads consistent..
