### ISSUE TITLE
Generate coverage2cytosine reports

### ISSUE THREAD

**Issue by jarcasariego** [sr320/ceabigr#59]
@kubu4 can you help me running coverage2cytosines on the bismark output?

**Comment by kubu4** [comment]
What kind of help do you need?

**Comment by sr320** [comment]
We have the `*CpG_report.merged_CpG_evidence.cov` files 
at
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/120321-cvBS/

is that what you are looking for?

**Comment by jarcasariego** [comment]
you do? I did not see it, sorry. Yes, that is exactly what I need. Thank you both
