### ISSUE TITLE
RStudio server working for other people?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/ceabigr#63]
I can't connect to the RStudio server right now. I have Husky OnNet running as usual, so curious if other folks are able to access the RStudio server?

**Comment by sr320** [comment]
I will need to reset your access to Husky OnNet.. will do that now.

**Comment by sr320** [comment]
never mind on that - Sam has you OnNet service....

**Comment by kubu4** [comment]
One sec...

Any error messages or anything, or is it just not loading?

**Comment by sr320** [comment]
I think raven might be down at the moment. no ssh, etc. I am on campus and can reset if need be.

**Comment by kubu4** [comment]
Also, when restarting, you'll have to stick around to acknowledge the fan error message to complete boot.

**Comment by laurahspencer** [comment]
I'm in, thanks!
