### ISSUE TITLE
Compiling genetic data 

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#69]
add epidiverse to wiki

**Comment by sr320** [comment]
Sorry about that - got confused with ducks..

Yes if you could send C virg data through pipeline that would be great 
Yes - that is where bismark bams reside.

**Comment by kubu4** [comment]
This finished.

Directory is here:

https://gannet.fish.washington.edu/Atumefaciens/20220921-cvir-ceabigr-nextflow-epidiverse-snp/snps/stats/


Clustering is sort of interesting. Samples seperate out by sex, but there appear to be distinct clusters within each sex:

![image](https://user-images.githubusercontent.com/4514104/192320878-27bfe319-1d31-4f81-8dbc-82f0a2ba44f5.png)

**Comment by kubu4** [comment]
Probably should have linked the VCFs directory instead:

https://gannet.fish.washington.edu/Atumefaciens/20220921-cvir-ceabigr-nextflow-epidiverse-snp/snps/vcf/

Regardless, I'll get this info added to the wiki.

**Comment by kubu4** [comment]
Notebook: https://robertslab.github.io/sams-notebook/2022/09/21/BSseq-SNP-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-C.virginica-CEABIGR-BSseq-data.html

Wiki's been updated.
