### ISSUE TITLE
Revised SNP list

### ISSUE THREAD

**Issue by yaaminiv** [sr320/ceabigr#78]
At minimum, identifying C->T SNPs on both strands so we have a list of SNPs from the EpiDiverse output. 

Other tasks that build upon that:

- Compare Bs-snper and EpiDiverse SNP lists. Determine which source our final C->T SNP list should come from
- Remove SNPs from methylKit analysis
- Remove SNPs and recalculate average gene methylation and CV of gene methylation for modeling analyses

**Comment by sr320** [comment]
Just to confirm we have already removed CT SNPS from methylation data in the paper...
https://rpubs.com/sr320/1037429

Remind me why we need to revise the list?

**Comment by yaaminiv** [comment]
> Just to confirm we have already removed CT SNPS from methylation data in the paper...
https://rpubs.com/sr320/1037429

Correct! These were SNPs from BS-Snper.

> Remind me why we need to revise the list?

Based on conversations with Katherine during the workshop, the EpiDiverse/SNP workflow may be a more robust way of identifying SNPs from WGBS data. Additionally, we have RNA-Seq data we can also use to identify SNPs. We discussed comparing SNP identification between BS-Snper and EpiDiverse since we had the data, then maybe only removing SNPs identified using both methods unless there was a compelling reason to use one workflow over the other. So if we do revise the list of SNPs, we'll need to remove them again from the analyses.
