### ISSUE TITLE
Update mixomics analysis 

### ISSUE THREAD

**Issue by AHuffmyer** [sr320/ceabigr#82]
The mixomics figures and output look amazing Yaamini! Is there anything I can do to help with the correlation analysis for methylation and gene expression?

**Comment by yaaminiv** [comment]
I haven't been able to successfully tune the analysis yet and would appreciate help! I have the code already scripted here: https://github.com/sr320/ceabigr/blob/main/code/gene-methylation-expression-mixomics.Rmd

I couldn't get the code to run on the R Studio Server and I was [convinced I needed to run the code on mox instead](https://yaaminiv.github.io/CEABiGR-Part2/). I [tried running code on mox but was unsuccessful](https://yaaminiv.github.io/CEABiGR-Part6/).

**Comment by AHuffmyer** [comment]
I am also getting some errors with the tuning stages including `Error in Ypred[omit, , h] <- Y.hat[, , 1] : 
  number of items to replace is not a multiple of replacement length`. I'll look into this more this week.
