### ISSUE TITLE
Conduct spurious transcription analysis

### ISSUE THREAD

**Issue by yaaminiv** [sr320/ceabigr#85]
Analysis to understand "spuriousness" with respect to exon use suggested by Sam Bogan. Could we replicate this with our transcription data for each sex independently to look at treatment effects on exon use/spurious transcription?

---

Here's a [GitHub knit ](https://github.com/snbogan/Sp_RRBS_ATAC/blob/main/A_Differential_Exp_Splicing_Meth/A2_edgeR_DS_Sp_RRBS.md) of the code I used for measuring changes in exon use consistent with spuriousness (under the subheader "Determine which genes are..."). An .rmd file of the same name is also in this repo.

As an example of what these exon use patterns can look like, here's a plot of differential exon use induced by developmental or maternal stress across exon number. For some reason we saw that genes in the ATP synthase complex were enriched among transcripts exhibiting spurious transcription induced by stress. We don't know why, but that's why the plot says ATP synthase on it.

![image](https://github.com/sr320/ceabigr/assets/22335838/66f73e5a-449b-4ece-b0c2-5689c4cfc458)

**Comment by yaaminiv** [comment]
associated paper: https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-023-01645-8

**Comment by yaaminiv** [comment]
another option is to look at relative expression of exons: https://doi.org/10.1126/sciadv.aat2142

**Comment by kubu4** [comment]
From Li et al:

> Spurious transcription analysis
>
> Trimmed reads were mapped to the Aiptasia genome using HISAT2 v2.1.0, and mapping coverage per position was extracted using BEDTools v2.17.0. To assess spurious transcription levels, we determined the coverage per exon normalized across all six replicates (assuming every replicate had a coverage of 1 million sequences in total) and then calculated the average coverage ratios of exons 2 to 6 versus exon 1 for every gene.

@kubu4 Will get BAM files and link here.

**Comment by yaaminiv** [comment]
From Li et al.:

> To assess the level of spurious transcripts in genes of different methylation levels, we calculated the expression level for each exon and computed the natural log fold change of expression relative to exon1. Our rationale was that spurious transcripts that start somewhere within the gene body contribute more to observed increases in expression of more distal exons but less so to more proximal exons. Consequently, higher levels of spurious transcription would result in higher ratios of expression for more distal exons.

**Comment by yaaminiv** [comment]
From Li et al.:

> Trimmed reads were mapped to the Aiptasia genome using HISAT2 v2.1.0, and mapping coverage per position was extracted using BEDTools v2.17.0. To assess spurious transcription levels, we deter- mined the coverage per exon normalized across all six replicates (assuming every replicate had a coverage of 1 million sequences in total) and then calculated the average coverage ratios of exons 2 to 6 versus exon 1 for every gene

**Comment by yaaminiv** [comment]
Next step: create summary plot for all genes in all samples, but breakdown by methylation level:

 high (> 50%) vs. moderate (10-50%) vs. low (< 10%) methylation
