### ISSUE TITLE
Create exon regression per gene

### ISSUE THREAD

**Issue by kubu4** [sr320/ceabigr#86]

**Comment by kubu4** [comment]
Use this file to start:

https://github.com/sr320/ceabigr/blob/main/output/19-exon-expression/S12M-exon_expression.tab

**Comment by sr320** [comment]
With this code https://github.com/sr320/ceabigr/blob/main/code/64-exon-expression.Rmd

was able to get... 
https://github.com/sr320/ceabigr/blob/main/output/64-exon-expression/exon-summary.csv

still needs some follow - through to understand... get p values

**Comment by sr320** [comment]
quick look at data
![000128](https://github.com/sr320/ceabigr/assets/4442039/8917223a-5a1b-497d-b585-3a67ac3aaa67)

**Comment by kubu4** [comment]
From Li et al. Sci. Adv. 2018;4:eaat2142:

Spurious transcription calcs:

Compute natural log fold change of expression relative to exon 1.

> Higher levels of spurious transcription would result in higher ratios of expression for more distal exons.

This is due to their proposal that transcripts starting within the gene body would have increases in expression of more distal exons and less for more proximal exons.
