### ISSUE TITLE
examine potential for ASCA for exon analysis

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#90]

**Comment by AHuffmyer** [comment]
AH moving to this next - WGCNA presents some barriers as noted in issue #91

**Comment by AHuffmyer** [comment]
Genes for ground truthing 

List of 6 genes from PC1 (linear decreasing trend; no difference between treatment)
- LOC111124637
- LOC111134737
- LOC111133851
- LOC111118302
- LOC111138117
- LOC111118372

List of 6 genes from PC5 (higher in control and lower in exposed)
- LOC111124776
- LOC111100951
- LOC111119253
- LOC111119077
- LOC111136820
- LOC111126804

**Comment by AHuffmyer** [comment]
PC1 looks like this from ASCA: 

![Screenshot 2024-03-06 at 13 37 14](https://github.com/sr320/ceabigr/assets/32178010/66e83434-cd4f-4bf1-b47b-d0ec2460864a)

PC5 looks like this from ASCA:

![Screenshot 2024-03-06 at 13 37 02](https://github.com/sr320/ceabigr/assets/32178010/cbd50f48-79a9-4288-949f-a5249a53e627)

**Comment by AHuffmyer** [comment]
List of 6 genes from PC6 (opposite pattern of increase/decrease)
- LOC111106360
- LOC111137309
- LOC111137877
- LOC111136509
- LOC111121599
- LOC111118507

![Screenshot 2024-03-06 at 13 42 13](https://github.com/sr320/ceabigr/assets/32178010/d9a8a91a-c386-48cb-a010-08d84dbce628)

**Comment by AHuffmyer** [comment]
Results added to manuscript document and figures uploaded to repo

**Comment by AHuffmyer** [comment]
Notebook post with analysis: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/Analysis-of-Variance-Simultaneous-Component-Analyses-ASCA-for-CEABIGR-project/
