### ISSUE TITLE
Function enrichment for change max # transcript & predominant isoform

### ISSUE THREAD

**Issue by sr320** [sr320/ceabigr#94]

**Comment by sr320** [comment]
isoform done.......


still need list of genes in males and females where there was a change in max number of transcripts

**Comment by kubu4** [comment]
Females vs. Males:

https://github.com/sr320/ceabigr/blob/main/output/34-transcript-counts/diffs.max.transcripts_per_gene.females.vs.males.csv

Females Controls vs. Exposed:

https://github.com/sr320/ceabigr/blob/main/output/34-transcript-counts/diffs.max.transcripts_per_gene.controls_females.vs.exposed_females.csv

Males Controls vs. Exposed:

https://github.com/sr320/ceabigr/blob/main/output/34-transcript-counts/diffs.max.transcripts_per_gene.controls_males.vs.exposed_males.csv

These aren't the "final" lists. These still require filtering.

Here's the filtering method (genes are rows):

- If Column 3 < 0, Column 1 is < Column 2.
- If Column 3 > 0, Column 1 is > Column 2.

So, for the first file linked above (`diffs.max.transcripts_per_gene.females.vs.males.csv`), here's how the filtering criteria works:

- If Column 3 < 0, then males have higher number of max transcripts for a given gene.
- If Column 3 < 0, then females have a higher number of max transcripts for a given gene.

I can happily do the filtering an produce just the desired list(s). Just let me know.

**Comment by sr320** [comment]
At the end we want one table for males, one for females

```
x    Control MaxT #   Exposed MaxT #   Control Predom Isoform   Exposed Predome Isoform
Gene 1
Gene 2
Gene 3

```

**Comment by kubu4** [comment]
Yep, working on the combined table, per #93 .

**Comment by sr320** [comment]
If Column 3 < 0, then males have higher number of max transcripts for a given gene.
If Column 3 < 0, then females have a higher number of max transcripts for a given gene.

????

Seems same?

**Comment by kubu4** [comment]
But, basically, using the filename as a guide, it's always LEFT minus RIGHT. E.g.

`diffs.max.transcripts_per_gene.females.vs.males.csv`

This is comparing `females.vs.males`. So, the calculation is done FEMALES minus MALES.

Females will be Column 1 and males will be Column 2 in that file.

**Comment by yaaminiv** [comment]
@sr320 where's the code for the enrichment?

**Comment by yaaminiv** [comment]
Did functional enrichment with `topGO` for predominant isoforms.

- female sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/42-predominant-isoform/fem-predIso-BP-FisherTestResults.csv
- female sig BPGO with gene annotations: https://github.com/sr320/ceabigr/blob/main/output/42-predominant-isoform/fem-predIso-BP-EnrichedGO-geneAnnot.csv
- male sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/42-predominant-isoform/male-predIso-BP-FisherTestResults.csv
- male sig BPGO with gene annotations: https://github.com/sr320/ceabigr/blob/main/output/42-predominant-isoform/male-predIso-BP-EnrichedGO-geneAnnot.csv

Next step is examining methylation changes for genes with sig BPGO and repeating similar analysis for change in max transcripts

**Comment by yaaminiv** [comment]
Did functional enrichment wiht `topGO` for changes in the maximum transcript expressed

Females

- inc transcripts sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-maxTransPos-BP-FisherTestResults.csv
- inc transcripts sig BPGO with gene annotation: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-maxTransPos-BP-EnrichedGO-geneAnnot.csv
- dec transcripts sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-maxTransNeg-BP-FisherTestResults.csv
- dec transcripts sig BPGO with gene annotation: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/fem-maxTransNeg-BP-EnrichedGO-geneAnnot.csv
Males

- inc transcripts sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-maxTransPos-BP-FisherTestResults.csv
- inc transcripts sig BPGO with gene annotation: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-maxTransPos-BP-EnrichedGO-geneAnnot.csv
- dec transcripts sig BPGO: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-maxTransNeg-BP-FisherTestResults.csv
- dec transcripts sig BPGO with gene annotation: https://github.com/sr320/ceabigr/blob/main/output/75-max-transcript-enrichment/male-maxTransNeg-BP-EnrichedGO-geneAnnot.csv
